//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IstarWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IstarWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B/NJWh1fV5BPnGmg2edQ6GgK40Zs/L8I5HLfCRzKvupXKiRS7ASBF9Y5xXrM6OQzhUzKYLxKsIVunFyAL/kcRCdDaNpbwbqnfwV4dKV2Xkc=.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ogJu5MulGW0hv+tA3hF49FQiH5MZDlQrH6Dulpr+x50b7hHPwvZIV33XeIWFX8QCPsPX4jIWftDUbN+iLprWzA==.
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SET DATEFORMAT YMD
        ///USE [IstarRealEstate]
        ///GO
        ////****** Object:  Trigger [ReportInsertTrigger]    Script Date: 05.08.2015 8:15:32 ******/
        ///IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReportInsertTrigger]&apos;))
        ///DROP TRIGGER [dbo].[ReportInsertTrigger]
        ///GO
        ////****** Object:  Trigger [OrderInsertTrigger]    Script Date: 05.08.2015 8:15:32 ******/
        ///IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N&apos;[dbo].[OrderInsertTrigger]&apos;))
        ///DROP TRIGGER [dbo].[OrderInsertTrigger]
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SET DATEFORMAT YMD
        ///USE [IstarRealEstate]
        ///GO
        ////****** Object:  Trigger [ReportInsertTrigger]    Script Date: 14.09.2015 12:41:59 ******/
        ///IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReportInsertTrigger]&apos;))
        ///DROP TRIGGER [dbo].[ReportInsertTrigger]
        ///GO
        ////****** Object:  Trigger [OrderInsertTrigger]    Script Date: 14.09.2015 12:41:59 ******/
        ///IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N&apos;[dbo].[OrderInsertTrigger]&apos;))
        ///DROP TRIGGER [dbo].[OrderInsertTrigger] [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
    }
}
